// packages/react-dataflow-animator/src/DataFlowPlayer.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
// The only import that makes Vite emit `dist/style.css`, which `package.json`
// exports as `react-dataflow-animator/styles.css`. Dropping it ships a package
// with no stylesheet, silently.
//
// The stylesheet itself lives in the core now — it styles the core's renderer,
// not anything React draws. Until this package consumes the PUBLISHED core
// (step 3.2), it is pulled through the source alias and re-emitted here, so the
// same bytes ship twice: once as `@dataflow-animator/core/styles.css`, once as
// `react-dataflow-animator/styles.css`. 3.2 drops this import and points
// consumers at the core's stylesheet instead.
import '@dataflow-animator/core/styles/dataflow.css';
import type { CSSProperties } from 'react';
import type { DataFlowPlayerProps } from './types';
import { mountPlayer } from '@dataflow-animator/core/dom/player';
import { serializeSpec } from '@dataflow-animator/core/export/json';
import { toStyleMap } from './utils/styleMap';

/**
 * Main player: compiles a `spec` into a deterministic timeline and plays it.
 *
 * Since v3 this component is a MOUNT, not a renderer. It creates the
 * framework-agnostic DOM renderer from `@dataflow-animator/core` in an
 * effect and tears it down on unmount; React never manages the player's
 * children. That is what makes a frame ~6x cheaper: a clock tick mutates the
 * DOM in place instead of re-rendering a tree.
 *
 * Two consequences worth knowing:
 *
 *  - **No server markup.** The renderer needs a DOM, so the server emits only
 *    `fallback` (or an empty, correctly-sized box). There is no hydration
 *    mismatch because there is nothing to match.
 *  - **Every option is read once, at mount.** The core reads its options when it
 *    builds; changing any of them — `spec` included — remounts the player. The
 *    current instant and play state are carried across, so this is invisible
 *    while scrubbing or editing a spec.
 */

/**
 * `display: contents` removes the host's own box, so `.rdfa-player` inherits the
 * containing block the component itself was given — which is what `height="100%"`
 * needs, and what keeps the player a flex item of the same parent as before.
 */
const HOST_STYLE: CSSProperties = { display: 'contents' };

export function DataFlowPlayer({
  spec,
  className,
  style,
  height = 420,
  width,
  initialT = 0,
  autoPlay = false,
  loop = false,
  controls = true,
  exportable = false,
  theme = 'default',
  mode = 'auto',
  density = 'comfortable',
  debug = false,
  speed = 1,
  highlight,
  fallback,
}: DataFlowPlayerProps) {
  const hostRef = useRef<HTMLDivElement>(null);
  const [mounted, setMounted] = useState(false);

  // Read at mount only — see the prop docs. Held in refs so they can be current
  // without being dependencies.
  const specRef = useRef(spec);
  const highlightRef = useRef(highlight);

  // Synced in an effect rather than during render (writing a ref while
  // rendering is not safe under concurrent rendering). Declared BEFORE the
  // mount effect on purpose: effects run in declaration order, so by the time
  // the mount effect reads these refs they already hold this render's values.
  useEffect(() => {
    specRef.current = spec;
    highlightRef.current = highlight;
  });

  // Where a remount resumes from. Only the FIRST mount honours
  // `initialT`/`autoPlay`.
  const resumeRef = useRef<{ t: number; playing: boolean } | null>(null);

  /**
   * A STRUCTURAL key, not the object's identity.
   *
   * Callers routinely build the spec inline (`getSpec(demo, locale)` rebuilds it
   * on every render; a live editor reparses JSON on every keystroke), so keying
   * the effect on `spec` itself would tear the player down and remeasure on
   * every render of the enclosing page. `serializeSpec` is the same
   * serialisation the export dialog uses.
   */
  const specKey = useMemo(() => serializeSpec(spec), [spec]);
  const styleKey = useMemo(() => (style ? JSON.stringify(style) : ''), [style]);

  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;

    const resume = resumeRef.current;
    const player = mountPlayer(host, specRef.current, {
      height,
      width,
      className,
      theme,
      mode,
      density,
      controls,
      exportable,
      loop,
      speed,
      debug,
      style: toStyleMap(style),
      highlight: highlightRef.current,
      initialT: resume?.t ?? initialT,
      autoPlay: resume?.playing ?? autoPlay,
    });
    setMounted(true);

    if (debug && player.warnings.length)
      console.warn('[DataFlowAnimator]', ...player.warnings);

    return () => {
      // Captured BEFORE destroy: the clock is released in there.
      resumeRef.current = {
        t: player.clock.t,
        playing: player.clock.playing,
      };
      player.destroy();
    };
    // `highlight` and `spec` are intentionally absent: they are read through
    // refs, keyed by `specKey`. An inline `highlight={(c, l) => …}` would
    // otherwise be a new value on every render, and since every option change
    // remounts, the player would remount forever.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [
    specKey,
    styleKey,
    height,
    width,
    initialT,
    autoPlay,
    loop,
    controls,
    exportable,
    theme,
    mode,
    density,
    speed,
    className,
    debug,
  ]);

  const heightValue = typeof height === 'number' ? `${height}px` : height;
  const widthValue = typeof width === 'number' ? `${width}px` : width;

  return (
    <>
      {/*
        The placeholder is a SIBLING of the host, never its child: React owns
        this subtree and the core owns the host's, so the two renderers never
        contend for the same child list. It is rendered whether or not there is
        a `fallback` content, because it also reserves the player's box — without
        it the page would reflow when the real player appears.
      */}
      {mounted ? null : (
        <div
          className={`rdfa-player${className ? ` ${className}` : ''}`}
          data-theme={theme}
          data-mode={mode}
          style={{
            height: heightValue,
            ...(widthValue != null ? { width: widthValue } : {}),
            ...style,
          }}
        >
          {fallback ? (
            <div className="rdfa-stage rdfa-fallback">{fallback}</div>
          ) : null}
        </div>
      )}
      <div ref={hostRef} style={HOST_STYLE} />
    </>
  );
}

// packages/angular/src/DataFlowPlayerComponent.ts
import {
  Component,
  ElementRef,
  NgZone,
  PLATFORM_ID,
  computed,
  effect,
  inject,
  input,
  output,
  untracked,
} from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import {
  mountPlayer,
  serializeSpec,
  type DataFlowSpec,
  type Density,
  type Highlighter,
  type PlayerHandle,
  type PlayerLabels,
  type PlayerMode,
  type PlayerTheme,
} from '@dataflow-animator/core';
import { toPlayerOptions } from './options';

/**
 * `<dfa-player>` — the core's player as a standalone Angular component, in LIGHT
 * DOM.
 *
 * The component adds no rendering of its own: its template is empty, it calls
 * `mountPlayer(hostElement, spec, options)`, and the host element itself IS the
 * container, so the core's global `.rdfa-*` stylesheet applies with nothing to
 * pierce. The consumer imports `@dataflow-animator/core/styles.css` once; this
 * package ships no CSS, because the engine and the stylesheet are delivered once,
 * by the core, for every binding.
 *
 * Two things here exist only because the host is Angular, and nothing else in the
 * repository can catch either of them:
 *
 *  - **The rAF loop must not run inside the Angular zone.** The core's clock
 *    schedules a frame for as long as the player is playing; inside the zone that
 *    would trigger change detection on every single frame. `runOutsideAngular`
 *    around the mount is enough for the whole loop, because zone.js captures the
 *    zone when a frame is SCHEDULED and the clock reschedules from inside its own
 *    tick — which by then already runs outside. `zone.spec.ts` proves it by
 *    recording the zone at schedule time, and that test fails if this call is
 *    removed.
 *  - **Angular SSR is ordinary**, so the mount is guarded by
 *    `isPlatformBrowser`. Nothing here touches the DOM on a server — the same
 *    contract as the React binding's client effect and the custom element's
 *    conditional base class.
 *
 * Selector: `dfa-player`, NOT `dataflow-player`. That tag is a real custom
 * element registered globally by `@dataflow-animator/element`, and a consumer may
 * legitimately have both packages installed; a component matching a tag the
 * `CustomElementRegistry` also owns would mount two players into one host.
 */

/** Log prefix. A constant, so renaming the selector does not move it. */
const LOG = '[dfa-player]';

/** `mounted` payload — the compile warnings for the spec that was just mounted. */
export interface DataFlowPlayerMountedEvent {
  warnings: readonly string[];
}

/** `error` payload — parity with the custom element's `dataflow-player:error`. */
export interface DataFlowPlayerErrorEvent {
  error: unknown;
}

@Component({
  selector: 'dfa-player',
  // Empty, and it has to be: the core owns every child of the host element, so
  // Angular must not create any of its own. No `styles` either — a `:host { … }`
  // rule would put CSS in the published package, which is exactly what "the
  // stylesheet ships once, from the core" exists to prevent.
  template: '',
})
export class DataFlowPlayerComponent {
  /** The specification to play. Required. */
  readonly spec = input.required<DataFlowSpec>();

  readonly theme = input<PlayerTheme>();
  readonly mode = input<PlayerMode>();
  readonly density = input<Density>();
  /** A number is taken as pixels. Default (the core's): 420. */
  readonly height = input<number | string>();
  /** A number is taken as pixels. Omitted, the player takes its container's width. */
  readonly width = input<number | string>();
  /** An extra class on the `.rdfa-player` root (the core's `className` option). */
  readonly playerClass = input<string>();
  readonly speed = input<number>();
  readonly initialT = input<number>();
  readonly controls = input<boolean>();
  readonly exportable = input<boolean>();
  readonly autoPlay = input<boolean>();
  readonly loop = input<boolean>();
  readonly debug = input<boolean>();
  /** Custom syntax highlighting, replacing Prism. */
  readonly highlight = input<Highlighter>();
  /**
   * Localises the chrome — any key left out keeps the core's English default.
   * Keyed structurally, like `spec`: `[labels]="{ … }"` builds a fresh object
   * on every change detection pass, and keying on identity would remount the
   * player forever.
   */
  readonly labels = input<Partial<PlayerLabels>>();

  /** Emitted after every successful mount, remounts included. */
  readonly mounted = output<DataFlowPlayerMountedEvent>();
  /** Emitted when `mountPlayer` throws — reported, and no player is left behind. */
  readonly error = output<DataFlowPlayerErrorEvent>();

  private readonly host =
    inject<ElementRef<HTMLElement>>(ElementRef).nativeElement;
  private readonly zone = inject(NgZone);
  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  /**
   * Where a remount resumes from. Only the FIRST mount honours
   * `initialT`/`autoPlay`; every later one reopens at the instant and play state
   * the previous player was at, so changing an input while scrubbing is
   * invisible. Same contract as the React binding and the custom element.
   */
  private resume: { t: number; playing: boolean } | null = null;

  /**
   * A STRUCTURAL key for the spec, not the object's identity.
   *
   * This is the one Angular-specific hazard of the remount model: a template
   * writes `[spec]="buildSpec()"`, which produces a fresh object on every change
   * detection pass. Depending on the object would remount forever. `serializeSpec`
   * is the core's own serialisation — the same one the export dialog and the React
   * binding's `specKey` use.
   */
  private readonly specKey = computed(() => serializeSpec(this.spec()));

  /** Same hazard, same cure as `specKey` — see the `labels` input's doc. */
  private readonly labelsKey = computed(() =>
    JSON.stringify(this.labels() ?? null)
  );

  constructor() {
    // ONE effect for every option, which is what makes the remount coalesced:
    // however many inputs change in the same change detection pass, the effect
    // runs once, so the stage is measured once and no player is built to be
    // thrown away. `onCleanup` tears the previous one down — and it is the ONLY
    // teardown path, deliberately: effects are destroyed with the component, so an
    // `ngOnDestroy` doing the same thing would be a second path to the same
    // handle.
    effect((onCleanup) => {
      if (!this.isBrowser) return;

      // Tracked, and their values deliberately unused: this is what the effect
      // depends on for the spec and the labels. The objects themselves are read
      // untracked below.
      this.specKey();
      this.labelsKey();

      const options = toPlayerOptions({
        theme: this.theme(),
        mode: this.mode(),
        density: this.density(),
        height: this.height(),
        width: this.width(),
        playerClass: this.playerClass(),
        speed: this.speed(),
        initialT: this.initialT(),
        controls: this.controls(),
        exportable: this.exportable(),
        autoPlay: this.autoPlay(),
        loop: this.loop(),
        debug: this.debug(),
        // Untracked for the same reason React reads it through a ref: an inline
        // `[highlight]="(c, l) => …"` is a new function on every pass, and since
        // any change remounts, the player would remount forever.
        highlight: untracked(() => this.highlight()),
        // Untracked too, but NOT unwatched: `labelsKey` above re-runs the
        // effect when the content changes, identity aside.
        labels: untracked(() => this.labels()),
      });

      const resume = this.resume;
      if (resume) {
        options.initialT = resume.t;
        options.autoPlay = resume.playing;
      }

      // The same rule as the custom element's, character for character: an
      // unstyled element is `display: inline`, which would break `height="100%"`
      // and make the player a strange inline box. With no box of its own,
      // `.rdfa-player` inherits the containing block the tag was given. Only
      // applied when the author set NO inline display, so `style="display:block"`
      // opts out.
      if (this.host.style.display === '') this.host.style.display = 'contents';

      const spec = untracked(() => this.spec());
      let handle: PlayerHandle;
      try {
        // THE Angular-specific line. See the class comment.
        handle = this.zone.runOutsideAngular(() =>
          mountPlayer(this.host, spec, options)
        );
      } catch (error) {
        // Loud twice over, as in the custom element: a console message for the
        // developer and an event for a host that wants to surface it. A spec the
        // compiler rejects must not fail silently.
        console.error(`${LOG} mountPlayer failed:`, error);
        this.error.emit({ error });
        return;
      }

      // Registered BEFORE emitting: a listener must never be able to observe a
      // mounted player that has no teardown attached yet.
      onCleanup(() => {
        // Captured BEFORE destroy: the clock is released in there.
        this.resume = { t: handle.clock.t, playing: handle.clock.playing };
        handle.destroy();
      });

      if (options.debug && handle.warnings.length)
        console.warn(LOG, ...handle.warnings);

      // `runOutsideAngular` restored the zone, so this emission happens INSIDE
      // it — a consumer's handler that writes a signal gets change detection,
      // which it would not if the mount had leaked its zone to here.
      this.mounted.emit({ warnings: handle.warnings });
    });
  }
}
